### ISSUE TITLE
Highlight does not work unless attachTo is specified

### ISSUE THREAD

**Issue by erikkross** [pickhardt/Guiders-JS#110]
In version 2, the highlight option does not work on its own. You have to specify an attachTo value. If you just specify a highlight value, nothing is highlighted on the page. In version 1.3 this was not the case. 

This is somewhat of a problem in my app because I want to highlight a major portion of the page and show the guider on top of it, instead of attaching the guider to one of the sides. 

When I set highlight and attachTo and do not specify a position, the guider is set to be behind the highlight part of my app, so I am unable to see it. The z-index of the guider is 900001 and the z-index of the highlighted area is 900003. As a fix, I have set the guider z-index to be 900004 so it will always be above the highlighted area.

**Comment by pickhardt** [comment]
Thanks, fixed in master.
