### ISSUE TITLE
button onclick runs immediately

### ISSUE THREAD

**Issue by iateadonut** [pickhardt/Guiders-JS#120]
At this url: http://100wires.com/guiders/index.html#guider=3

I have this script:

```
<script>

function somef() {
        console.log('somef() has run');
}

$(document).ready(function() {

        guiders.createGuider({
                overlay: true,
            buttons: [{name: "Next"}],
            description: "meh",
            id: "3",
            next: "4",
            position: 3,
            title: "Click to create a customer for this request.",
        });

        guiders.createGuider({

                overlay: true,
            buttons: [{name: "Something", onclick: somef() }],
            description: "meh",
            id: "4",
            //next: "4",
            position: 3,
            title: "This is the next one.",
        });

});
</script>
```

The function somef() only logs to console that it has run.  In the code, you can see that somef() is only supposed to run when the button 'Something' on guider with id 4 is clicked.  However, if you go to the url with the hash, you can see in the console that somef() runs immediately.

**Comment by pickhardt** [comment]
That's because you are calling somef() instead of just writing `onclick: somef` (as a reference to somef).
